name: Release GrimmStats

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow

      - name: Build GrimmStats.exe
        shell: pwsh
        run: |
          python -m PyInstaller --noconfirm --clean --onefile --windowed --name GrimmStats --add-data "version.json;." --icon icon.ico --add-data "icon.ico;." main.py

      - name: Get version from tag
        id: get_version
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          echo "TAG=$tag" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG }}
          name: ${{ steps.get_version.outputs.TAG }}
          body: "Auto build ${{ steps.get_version.outputs.TAG }}"
          files: dist/GrimmStats.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.json in main branch
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git pull origin main
          
          # Обновляем exe_url в version.json
          $versionFile = "version.json"
          if (Test-Path $versionFile) {
              $obj = Get-Content $versionFile | ConvertFrom-Json
              $obj.exe_url = "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.TAG }}/GrimmStats.exe"
              $obj | ConvertTo-Json -Depth 3 | Set-Content $versionFile -Encoding UTF8
              
              git add $versionFile
              git diff-index --quiet HEAD || git commit -m "Update manifest for ${{ steps.get_version.outputs.TAG }} [skip ci]"
              git push origin main
          }
